=== PabloMateosP/Examen_LMSGI/Ejercicio1_Examen/pedido1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Pedidos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pedido">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cod_sucursal" type="xs:string"/>
                            <xs:element name="nom_trabajador" type="xs:string"/>
                            <xs:element name="fec_pedidos" type="xs:date"/>
                            <xs:element name="observaciones" type="xs:string"/>
                            <xs:element name="articulos">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="num" type="xs:int"/>
                                        <xs:element name="precio" type="xs:int"/>
                                        <xs:element name="observarcion" type="xs:string"/>
                                        <xs:element name="revision" type="xs:int"/>
                                    </xs:sequence>
                                    <xs:attribute name="code" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== PabloMateosP/Examen_LMSGI/Ejercicio1_Examen/pedido1.xml
<?xml version="1.0" encoding="UTF-8"?>
<Pedidos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="pedido1.xsd">
    <Pedido>
        <cod_sucursal>A9865434</cod_sucursal>
        <nom_trabajador>Francisco Montero Gutierrez</nom_trabajador>
        <fec_pedidos>2020-01-01</fec_pedidos>
        <observaciones>Urgente</observaciones>
        <articulos code="ADE-123">
            <num>12</num>
            <precio>270</precio>
            <observarcion>El artículo llegó en su fecha esperada</observarcion>
            <revision>15</revision>
        </articulos>
    </Pedido>
</Pedidos>
